import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';

const latoSans = Lato({
  variable: '--font-lato-sans',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

const latoMono = Lato({
  variable: '--font-lato-mono',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: 'normal',
  display: 'swap',
  fallback: ['monospace'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{}>;
}>) {
  await params; // Await params even though it's empty
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${latoSans.variable} ${latoMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
