/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

import './globals.css'

const latoSans = Lato({
  variable: '--font-lato-sans',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})

const latoMono = Lato({
  variable: '--font-lato-mono',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: 'normal',
  display: 'swap',
  fallback: ['monospace'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${latoSans.variable} ${latoMono.variable}`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  )
}
